INSERT INTO persons (FIRST_NAME, LAST_NAME) VALUES ('Mati', 'Mets');
INSERT INTO persons (FIRST_NAME, LAST_NAME) VALUES ('Kati', 'Karu');
INSERT INTO persons (FIRST_NAME, LAST_NAME) VALUES ('Sven', 'Kaasik');
INSERT INTO persons (FIRST_NAME, LAST_NAME) VALUES ('Liisi', 'Hunt');
INSERT INTO persons (FIRST_NAME, LAST_NAME, PARENT1_ID, PARENT2_ID) VALUES ('Tiina', 'Mets', 1, 2);
INSERT INTO persons (FIRST_NAME, LAST_NAME, PARENT1_ID, PARENT2_ID) VALUES ('Liina', 'Mets', 1, 2);
INSERT INTO persons (FIRST_NAME, LAST_NAME, PARENT1_ID, PARENT2_ID) VALUES ('Toomas', 'Kaasik', 3, 4);
INSERT INTO persons (FIRST_NAME, LAST_NAME, PARENT1_ID, PARENT2_ID) VALUES ('Tanel', 'Mets', 1, 4);